const APP_KEY='draftforge-v8-5-turn-aware-state';
const PROFILE_KEY='draftforge-v8-5-profile';
let engine;
let filter='ALL';
let screenshotFiles=[];
let reviewPicks=[];
const NFL_TEAMS=['ARI','ATL','BAL','BUF','CAR','CHI','CIN','CLE','DAL','DEN','DET','GB','HOU','IND','JAX','KC','LAC','LAR','LV','MIA','MIN','NE','NO','NYG','NYJ','PHI','PIT','SEA','SF','TB','TEN','WAS'];

function clone(x){return JSON.parse(JSON.stringify(x))}
function qs(id){return document.getElementById(id)}
function escapeHtml(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function showToast(msg){const t=qs('toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast._t);showToast._t=setTimeout(()=>t.classList.remove('show'),2600)}
function save(){localStorage.setItem(APP_KEY,JSON.stringify(engine.serialize()))}
function boot(){
  const league=clone(DRAFTFORGE_PRESETS['User Yahoo League']);
  engine=new DraftForgeEngine(DRAFTFORGE_PLAYERS,league);
  try{const s=JSON.parse(localStorage.getItem(APP_KEY)||'null');if(s)engine.hydrate(s)}catch{}
  rebuildSlotSelect();rebuildFilters();rebuildPresetSelect();rebuildWeekSelect();rebuildPlayerNames();render();
  if('serviceWorker'in navigator && location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
}
function rebuildSlotSelect(){const el=qs('slotSelect'),tc=engine.teamCount(),cur=engine.slot||'';el.innerHTML='<option value="">Choose…</option>'+Array.from({length:tc},(_,i)=>`<option value="${i+1}">${i+1}</option>`).join('');el.value=cur}
function rebuildFilters(){const arr=['ALL','QB','RB','WR','TE','DST','K','FAV'];qs('positionFilters').innerHTML=arr.map(x=>`<button class="filter ${x===filter?'active':''}" onclick="setFilter('${x}')">${x}</button>`).join('')}
function setFilter(x){filter=x;rebuildFilters();renderBoard()}
function rebuildPresetSelect(){qs('presetSelect').innerHTML=Object.keys(DRAFTFORGE_PRESETS).map(k=>`<option value="${escapeHtml(k)}">${escapeHtml(k)}</option>`).join('')}
function rebuildWeekSelect(){qs('weekSelect').innerHTML=Array.from({length:18},(_,i)=>`<option value="${i+1}">Week ${i+1}</option>`).join('')}
function rebuildPlayerNames(){qs('playerNames').innerHTML=DRAFTFORGE_PLAYERS.map(p=>`<option value="${escapeHtml(p.name)}"></option>`).join('')}
function switchView(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===view));const titles={draft:'Draft Room',team:'My Team',lineup:'Lineup Optimizer',analytics:'Draft Analytics'};qs('viewTitle').textContent=titles[view]||'DraftForge';if(view==='team')renderTeam();if(view==='lineup')renderLineup();if(view==='analytics')renderAnalytics();scrollTo({top:0,behavior:'smooth'})}
function setSlot(){engine.slot=+qs('slotSelect').value||null;save();render()}
function startMock(){if(!engine.slot)return showToast('Choose your draft slot first.');engine.reset();engine.autoToMyPick();save();render();showToast(`Mock started from slot ${engine.slot}.`)}
function undoDraft(){if(!engine.undo())return showToast('Nothing to undo.');save();render()}
function takeRecommended(){const a=engine.recs(1)[0];if(!a)return;if(engine.teamForOverall(engine.overall)!==engine.slot)return showToast('It is not your pick yet.');engine.myChoose(a.p.id);engine.autoToMyPick();save();render()}
function takePlayer(id){if(!engine.slot)return showToast('Choose a draft slot first.');if(engine.teamForOverall(engine.overall)!==engine.slot)return showToast('It is not your pick yet.');if(!engine.myChoose(id))return;engine.autoToMyPick();save();render()}
function markDrafted(id){const team=engine.teamForOverall(engine.overall),mine=team===engine.slot;engine.choose(id,team,mine);save();render()}
function toggleFav(id){engine.favorites[id]=!engine.favorites[id];save();render()}
function render(){renderHeader();renderRecommendations();renderRoster();renderOpponentIntel();renderBoard();renderTeam();renderAnalytics()}
function renderHeader(){
  const league=engine.league,round=engine.roundFor(engine.overall),total=engine.totalRosterSize(),team=engine.teamForOverall(engine.overall),nx=engine.nextMine(),away=nx?Math.max(0,nx-engine.overall):null;
  qs('leagueTitle').textContent=league.name||'Fantasy Draft';qs('leagueSubtitle').textContent=`${engine.teamCount()}-Team ${(+league.scoring?.rec||0)===1?'PPR':(+league.scoring?.rec||0)===.5?'Half PPR':'Custom'} Snake Draft`;
  qs('roundStat').textContent=`${Math.min(round,total)} / ${total}`;qs('overallStat').textContent=`Pick ${Math.min(engine.overall,engine.maxPicks())}`;
  qs('clockOwner').textContent=engine.isComplete()?'Draft complete':!engine.slot?'Choose slot':team===engine.slot?'YOU':`Team ${team}`;qs('clockPick').textContent=engine.isComplete()?'Final roster locked':`Overall ${engine.overall}`;
  qs('picksAway').textContent=away===null?'—':away;qs('nextMineStat').textContent=nx?`Next: ${nx}`:'No remaining picks';
}
function renderRecommendations(){
  const recs=engine.recs(5);if(!recs.length){qs('recommendations').innerHTML='<div class="subtle">No recommendations available.</div>';return}
  qs('recommendations').innerHTML=recs.map(({p,s},i)=>{const sv=engine.nextPickSurvival(p),d=engine.turnDecision(p),tp=engine.playerTurnPressure(p);return `<div class="rec"><div class="rec-rank">${i+1}</div><div><div class="player-name">${escapeHtml(p.name)}</div><div class="player-meta">${p.team} • ${p.pos}${p.posRank} • Rank ${p.rank}${p.news?` • ${escapeHtml(p.trend||'NEWS')}`:''}</div></div><div class="rec-extra"><div class="label">Score</div><div class="score-pill">${s.toFixed(1)}</div></div><div class="rec-extra"><div class="label">Survive</div><strong>${sv===null?'—':Math.round(sv*100)+'%'}</strong></div><div class="rec-extra"><div class="label">Pressure</div><strong class="risk-${tp.label}">${tp.label}</strong></div><div><span class="turn-badge ${d.cls}" title="${escapeHtml(d.text)}">${d.label}</span>${engine.teamForOverall(engine.overall)===engine.slot?`<button class="button compact" style="margin-top:5px;width:100%" onclick="takePlayer('${p.id}')">Draft</button>`:''}</div></div>`}).join('')
}
function positionStrength(pos){const list=engine.myPlayers().filter(p=>p.pos===pos);if(!list.length)return 0;const avg=list.reduce((a,p)=>a+Math.max(0,110-p.rank),0)/list.length;return Math.max(5,Math.min(100,Math.round(avg)))}
function renderRoster(){
  const list=engine.myPlayers(),c=engine.counts(list),defs=[['QB',engine.requiredQB()],['RB',engine.requiredRB()],['WR',engine.requiredWR()],['TE',engine.requiredTE()],['DST',+engine.league.slots?.DST||0]];
  qs('positionStrengths').innerHTML=defs.filter(x=>x[1]>0).map(([p,n])=>{const st=positionStrength(p);return `<div class="strength-row"><b>${p}</b><div class="bar"><i style="width:${st}%"></i></div><span>${c[p]||0}</span></div>`}).join('');
  const needs=defs.filter(([p,n])=>(c[p]||0)<n).map(([p,n])=>p);qs('teamNeeds').innerHTML=needs.length?needs.map(p=>`<span class="chip hot">${p}</span>`).join(''):'<span class="chip">Core starters covered</span>';
  qs('rosterPeek').innerHTML=list.length?list.slice(-8).reverse().map(p=>`<div class="roster-mini"><span><b class="pos ${p.pos}">${p.pos}</b> ${escapeHtml(p.name)}</span><small>#${p.rank}</small></div>`).join(''):'<div class="subtle">No players drafted yet.</div>';
  const required=defs.filter(x=>x[1]>0),coverage=required.reduce((a,[p,n])=>a+Math.min(c[p]||0,n)/n,0)/Math.max(1,required.length),value=list.length?list.reduce((a,p)=>a+Math.max(0,100-p.rank)/100,0)/list.length:0;const total=Math.round((coverage*.72+value*.28)*100);qs('rosterGrade').textContent=total>=90?'A':total>=80?'B+':total>=70?'B':total>=58?'C':'—';
}
function renderOpponentIntel(){
  const seq=engine.interveningPickSequence();if(!seq.length){qs('opponentIntel').innerHTML='<div class="subtle">Choose a slot or make your pick to see who is between your turns.</div>';return}
  const seen=[];for(const q of seq){if(!seen.includes(q.team))seen.push(q.team)}
  qs('opponentIntel').innerHTML=seen.slice(0,12).map(team=>{const c=engine.counts(engine.teamRoster(team)),needs=[];if(c.QB<engine.requiredQB())needs.push('QB');if(c.RB<engine.requiredRB()+1)needs.push('RB');if(c.WR<engine.requiredWR()+1)needs.push('WR');if(c.TE<engine.requiredTE())needs.push('TE');const picks=seq.filter(q=>q.team===team).map(q=>q.overall).join(', ');return `<div class="opp"><small>Team ${team} • picks ${picks}</small><strong>${needs.length?needs.join(' / '):'Bench value'}</strong><small>${c.QB} QB • ${c.RB} RB • ${c.WR} WR • ${c.TE} TE</small></div>`}).join('')
}
function renderBoard(){
  const q=(qs('search')?.value||'').trim().toLowerCase();let arr=engine.avail().filter(p=>(filter==='ALL'||p.pos===filter||(filter==='FAV'&&engine.favBonus(p)>0))&&(!q||p.name.toLowerCase().includes(q)||p.team.toLowerCase().includes(q))).sort((a,b)=>a.rank-b.rank);qs('boardCount').textContent=`${arr.length} available`;
  qs('boardBody').innerHTML=arr.slice(0,292).map(p=>{const sv=engine.nextPickSurvival(p),d=engine.turnDecision(p),allowed=engine.candidateAllowed(p),score=allowed?engine.score(p):null;return `<tr><td><button class="fav ${engine.favorites[p.id]?'on':''}" onclick="toggleFav('${p.id}')">★</button> ${p.rank}</td><td><b>${escapeHtml(p.name)}</b><div class="player-meta">${p.team}${p.news?` • ${escapeHtml(p.news)}`:''}</div></td><td><span class="pos ${p.pos}">${p.pos}${p.posRank}</span></td><td>T${p.tier}</td><td>${score===null?'—':score.toFixed(1)}</td><td>${sv===null?'—':Math.round(sv*100)+'%'}</td><td><span class="turn-badge ${d.cls}">${d.label}</span></td><td>${engine.teamForOverall(engine.overall)===engine.slot&&allowed?`<button class="button compact" onclick="takePlayer('${p.id}')">Take</button>`:`<button class="button compact" onclick="markDrafted('${p.id}')">Gone</button>`}</td></tr>`}).join('')
}
function renderTeam(){
  const list=engine.myPlayers(),c=engine.counts(list);qs('fullRoster').innerHTML=list.length?`<div class="roster-table">${list.map((p,i)=>`<div class="roster-line"><b>${p.pos}</b><span>${escapeHtml(p.name)}</span><span>${p.team}</span><small>R${engine.picks.find(x=>x.id===p.id)?.overall||'—'}</small></div>`).join('')}</div>`:'<div class="subtle">No roster yet.</div>';
  const all=['QB','RB','WR','TE','DST','K'];qs('teamCounts').innerHTML=all.map(pos=>`<div class="count-card"><b>${pos}</b><div class="bar"><i style="width:${Math.min(100,(c[pos]||0)*22)}%"></i></div><strong>${c[pos]||0}</strong></div>`).join('')
}
function stableHash(str){let h=2166136261;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h>>>0)}
function pseudoOpponent(p,week){const idx=(stableHash(p.team+week)+week*7)%NFL_TEAMS.length;let opp=NFL_TEAMS[idx];if(opp===p.team)opp=NFL_TEAMS[(idx+3)%NFL_TEAMS.length];return opp}
function baseWeeklyProjection(p){const r=p.posRank||p.rank||99;if(p.pos==='QB')return Math.max(8,24.5-(r-1)*.45);if(p.pos==='RB')return Math.max(4,19-(r-1)*.31);if(p.pos==='WR')return Math.max(4,18.5-(r-1)*.27);if(p.pos==='TE')return Math.max(3,15-(r-1)*.32);if(p.pos==='DST')return Math.max(4,9.5-(r-1)*.18);if(p.pos==='K')return Math.max(4,9-(r-1)*.15);return 5}
function weeklyData(p,week){let variance=((stableHash(p.id+':'+week)%1000)/1000-.5)*4.4,projection=baseWeeklyProjection(p)+variance+engine.scoringMods(p)*.45,status=p.news?'Questionable':'Active';if(status==='Questionable')projection*=.90;return{projection:Math.max(0,projection),floor:Math.max(0,projection*.70),ceiling:projection*1.36,opponent:pseudoOpponent(p,week),status}}
function lineupSlots(){const s=engine.league.slots||{},out=[];const add=(label,n,eligible)=>{for(let i=0;i<n;i++)out.push({label: n>1?`${label}${i+1}`:label,eligible})};add('QB',+s.QB||0,['QB']);add('RB',+s.RB||0,['RB']);add('WR',+s.WR||0,['WR']);add('TE',+s.TE||0,['TE']);add('FLEX',+s.FLEX||0,['RB','WR','TE']);add('SF',+s.SUPERFLEX||0,['QB','RB','WR','TE']);add('DST',+s.DST||0,['DST']);add('K',+s.K||0,['K']);return out}
function renderLineup(){const list=engine.myPlayers(),week=+qs('weekSelect').value||1,mode=qs('lineupMode').value||'balanced',used=new Set(),cards=[];for(const slot of lineupSlots()){const candidates=list.filter(p=>slot.eligible.includes(p.pos)&&!used.has(p.id)).map(p=>{const d=weeklyData(p,week),v=mode==='floor'?d.floor*.72+d.projection*.28:mode==='ceiling'?d.ceiling*.70+d.projection*.30:d.projection;return{p,d,v}}).sort((a,b)=>b.v-a.v);const a=candidates[0];if(a)used.add(a.p.id);cards.push(`<div class="lineup-slot"><span>${slot.label}</span><strong>${a?escapeHtml(a.p.name):'Open slot'}</strong><small>${a?`${a.p.team} vs ${a.d.opponent} • ${a.d.projection.toFixed(1)} proj`:'Draft a player'}</small></div>`)}qs('lineupOutput').innerHTML=list.length?`<div class="lineup-grid">${cards.join('')}</div>`:'<div class="subtle">Draft a roster first.</div>'}
function renderAnalytics(){const drafted=engine.picks.map(x=>engine.pby(x.id)).filter(Boolean),c=engine.counts(drafted),mx=Math.max(1,...['QB','RB','WR','TE','DST','K'].map(p=>c[p]||0));qs('positionAnalytics').innerHTML=['QB','RB','WR','TE','DST','K'].map(p=>`<div class="analytics-bar"><b>${p}</b><div class="bar"><i style="width:${(c[p]||0)/mx*100}%"></i></div><span>${c[p]||0}</span></div>`).join('');const mine=engine.myPlayers();if(!mine.length){qs('valueAnalytics').innerHTML='<div class="subtle">No picks yet.</div>';return}const rows=mine.map(p=>{const pick=engine.picks.find(x=>x.id===p.id)?.overall||0,value=pick-p.rank;return{p,pick,value}}).sort((a,b)=>b.value-a.value);qs('valueAnalytics').innerHTML=rows.map(x=>`<div class="roster-mini"><span>${escapeHtml(x.p.name)} <small>pick ${x.pick}</small></span><b style="color:${x.value>=0?'var(--green)':'var(--red)'}">${x.value>=0?'+':''}${x.value}</b></div>`).join('')}
function openModal(id){qs(id).classList.add('open');qs(id).setAttribute('aria-hidden','false')}
function closeModal(id){qs(id).classList.remove('open');qs(id).setAttribute('aria-hidden','true')}
function openLeagueSetup(){openModal('leagueModal');loadLeagueToForm(engine.league)}
function loadPresetIntoForm(){loadLeagueToForm(DRAFTFORGE_PRESETS[qs('presetSelect').value])}
function loadLeagueToForm(l){qs('leagueTeams').value=l.teams;qs('slotQB').value=l.slots.QB||0;qs('slotSF').value=l.slots.SUPERFLEX||0;qs('slotRB').value=l.slots.RB||0;qs('slotWR').value=l.slots.WR||0;qs('slotTE').value=l.slots.TE||0;qs('slotFlex').value=l.slots.FLEX||0;qs('slotDST').value=l.slots.DST||0;qs('slotK').value=l.slots.K||0;qs('slotBench').value=l.bench||0;qs('scoringRec').value=l.scoring?.rec??1}
function applyLeagueForm(){const l=clone(engine.league);l.teams=+qs('leagueTeams').value||12;l.slots={...l.slots,QB:+qs('slotQB').value||0,SUPERFLEX:+qs('slotSF').value||0,RB:+qs('slotRB').value||0,WR:+qs('slotWR').value||0,TE:+qs('slotTE').value||0,FLEX:+qs('slotFlex').value||0,DST:+qs('slotDST').value||0,K:+qs('slotK').value||0};l.bench=+qs('slotBench').value||0;l.scoring={...l.scoring,rec:+qs('scoringRec').value||0};engine.league=l;engine.ensureTeams();engine.reset();rebuildSlotSelect();save();closeModal('leagueModal');render();showToast('League settings applied; draft reset.')}
function openScreenshotSync(){openModal('screenshotModal');renderScreenshotReview()}
function handleScreenshotFiles(files){for(const f of files||[])if(f.type.startsWith('image/'))screenshotFiles.push(f);renderScreenshotReview()}
function renderScreenshotReview(){qs('screenshotQueue').innerHTML=screenshotFiles.length?screenshotFiles.map((f,i)=>`<div class="preview-item"><span>${escapeHtml(f.name||`Screenshot ${i+1}`)}</span><button class="icon" onclick="removeScreenshot(${i})">✕</button></div>`).join(''):'<div class="subtle">No screenshots queued.</div>';qs('reviewPicks').innerHTML=reviewPicks.length?reviewPicks.sort((a,b)=>a.pick-b.pick).map((x,i)=>`<div class="review-item"><span>#${x.pick} • <b>${escapeHtml(x.name)}</b> ${x.matched?`→ ${escapeHtml(x.matched.name)}`:'(unmatched)'}</span><button class="icon" onclick="removeReviewPick(${i})">✕</button></div>`).join(''):'<div class="subtle">No reviewed picks yet.</div>';qs('screenshotStatus').textContent=`${reviewPicks.length} reviewed pick${reviewPicks.length===1?'':'s'}.`}
function removeScreenshot(i){screenshotFiles.splice(i,1);renderScreenshotReview()}
function removeReviewPick(i){reviewPicks.splice(i,1);renderScreenshotReview()}
function fuzzyPlayer(name){const norm=s=>s.toLowerCase().replace(/[^a-z0-9]/g,'');const n=norm(name);let exact=DRAFTFORGE_PLAYERS.find(p=>norm(p.name)===n);if(exact)return exact;return DRAFTFORGE_PLAYERS.find(p=>norm(p.name).includes(n)||n.includes(norm(p.name)))||null}
function addManualReviewPick(){const pick=+qs('manualPickNo').value,name=qs('manualPlayer').value.trim();if(!pick||!name)return showToast('Enter a pick number and player name.');reviewPicks.push({pick,name,matched:fuzzyPlayer(name)});qs('manualPickNo').value=pick+1;qs('manualPlayer').value='';renderScreenshotReview()}
async function analyzeScreenshots(){if(!screenshotFiles.length)return showToast('Add at least one screenshot first.');const fd=new FormData();screenshotFiles.forEach(f=>fd.append('images',f));try{const r=await fetch('/api/screenshot/analyze',{method:'POST',body:fd});if(!r.ok)throw new Error((await r.text())||`HTTP ${r.status}`);const data=await r.json();for(const x of data.picks||[])reviewPicks.push({pick:+x.pick,name:x.name,matched:fuzzyPlayer(x.name)});renderScreenshotReview();showToast('Screenshot analysis loaded for review.')}catch(e){showToast('Server analyzer is not configured. Use manual fallback.')}}
function applyReviewedPicks(){const rows=reviewPicks.filter(x=>x.matched&&!engine.drafted[x.matched.id]).sort((a,b)=>a.pick-b.pick);if(!rows.length)return showToast('No matched picks to apply.');for(const x of rows){if(x.pick<engine.overall)continue;while(engine.overall<x.pick){const p=engine.avail()[0];if(!p)break;engine.choose(p.id,engine.teamForOverall(engine.overall),engine.teamForOverall(engine.overall)===engine.slot)}engine.choose(x.matched.id,engine.teamForOverall(engine.overall),engine.teamForOverall(engine.overall)===engine.slot)}save();render();closeModal('screenshotModal');showToast(`${rows.length} confirmed picks applied.`)}
function openYahooSync(){openModal('yahooModal')}
async function syncYahooNow(){try{const leagueId=engine.league.leagueId||'846890',r=await fetch(`/api/yahoo/picks?leagueId=${encodeURIComponent(leagueId)}`);if(!r.ok)throw new Error('Yahoo server not configured');const data=await r.json();let applied=0;for(const x of data.picks||[]){const p=fuzzyPlayer(x.name);if(p&&!engine.drafted[p.id]){engine.choose(p.id,engine.teamForOverall(engine.overall),engine.teamForOverall(engine.overall)===engine.slot);applied++}}save();render();showToast(`Yahoo sync applied ${applied} new picks.`)}catch{showToast('Yahoo server sync is not configured on this deployment.')}}
async function copyDraftState(){const payload=JSON.stringify({version:'8.5',overall:engine.overall,slot:engine.slot,picks:engine.picks.map(x=>({...x,name:engine.pby(x.id)?.name}))},null,2);try{await navigator.clipboard.writeText(payload);showToast('Draft state copied.')}catch{prompt('Copy draft state:',payload)}}
window.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal.open').forEach(m=>closeModal(m.id))});
window.addEventListener('DOMContentLoaded',boot);
